name: Scaleway Config
version: 1.0.0
schema: v1
models:
  - name: Scaleway Qwen 3.6 35B
    provider: scaleway
    model: qwen3.6-35b-a3b
    apiKey: 48fdd374-774a-441e-9c83-ba09a28fc591
    apiBase: https://api.scaleway.ai/f005eae3-be4a-4071-bef6-e656478635c2/v1
    contextLength: 32768
    maxTokens: 4096
    parameters:
      reasoning_effort: medium
      presence_penalty: 0
      temperature: 0.6
      top_p: 0.95
    roles:
      - chat
      - edit
      - apply
    requestOptions:
      body:
        reasoning_effort: medium
        temperature: 0.6
        top_p: 0.95
        presence_penalty: 0
  - name: Scaleway Qwen 3 Coder 30B
    provider: scaleway
    model: qwen3-coder-30b-a3b-instruct
    apiKey: 48fdd374-774a-441e-9c83-ba09a28fc591
    apiBase: https://api.scaleway.ai/f005eae3-be4a-4071-bef6-e656478635c2/v1
    contextLength: 32768
    maxTokens: 4096
    systemMessage: When editing or applying code, output ONLY valid code blocks. Do
      not include conversational intro, outro, or explanations.
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    requestOptions:
      body:
        reasoning_effort: none
        temperature: 0.1
        top_p: 0.8
        presence_penalty: 0
  - name: Scaleway Gemma 4 26B
    provider: scaleway
    model: gemma-4-26b-a4b-it
    apiBase: https://api.scaleway.ai/f005eae3-be4a-4071-bef6-e656478635c2/v1
    apiKey: 48fdd374-774a-441e-9c83-ba09a28fc591
    roles:
      - chat
      - edit
      - apply
    requestOptions:
      body:
        reasoning_effort: medium
        temperature: 1
        top_p: 0.95
        presence_penalty: 0
  - name: Scaleway Llama 3.3 Instruct 70B
    provider: scaleway
    model: llama-3.3-70b-instruct
    apiBase: https://api.scaleway.ai/f005eae3-be4a-4071-bef6-e656478635c2/v1
    apiKey: 48fdd374-774a-441e-9c83-ba09a28fc591
    maxTokens: 16384
    systemMessage: When editing or applying code, output ONLY valid code blocks. Do
      not include conversational intro, outro, or explanations.
    roles:
      - chat
      - edit
      - apply
      - tool_use
    requestOptions:
      body:
        temperature: 0.6
        top_p: 0.9
        presence_penalty: 0
  - name: Scaleway Mistral Small 3.2 24B Instruct
    provider: scaleway
    model: mistral-small-3.2-24b-instruct-2506
    apiBase: https://api.scaleway.ai/f005eae3-be4a-4071-bef6-e656478635c2/v1
    apiKey: 48fdd374-774a-441e-9c83-ba09a28fc591
    systemMessage: When editing or applying code, output ONLY valid code blocks. Do
      not include conversational intro, outro, or explanations.
    maxTokens: 2048
    roles:
      - edit
      - apply
      - tool_use
    requestOptions:
      body:
        reasoning_effort: none
        temperature: 0.15
        top_p: 1
        presence_penalty: 0
  - name: Llama3.1 8b Chat
    provider: scaleway
    model: llama3.1-8b
    apiKey: 48fdd374-774a-441e-9c83-ba09a28fc591
  - name: Llama3.1 8b Chat (1)
    provider: scaleway
    model: llama3.1-8b
    apiKey: 48fdd374-774a-441e-9c83-ba09a28fc591
  - name: Llama3.1 70b Chat
    provider: scaleway
    model: llama3.1-70b
    apiKey: 48fdd374-774a-441e-9c83-ba09a28fc591
tabAutocompleteModel:
  title: Scaleway Mistral Small 3.2 24B Instruct
  provider: openai
  model: qwen3-coder-30b-a3b-instruct
  apiBase: https://api.scaleway.ai/f005eae3-be4a-4071-bef6-e656478635c2/v1
  contextLength: 2048
